### ISSUE TITLE
Pon un icono decente hijo de puta

### ISSUE THREAD

**Issue by ivoriginal** [CodingCarlos/inapp-support#14]
https://storage.googleapis.com/material-icons/external-assets/v4/icons/svg/ic_chat_bubble_black_24px.svg

**Comment by CodingCarlos** [comment]
Thank you, ma'friend, I guess you mean the fab button icon. I didn't even though on it. I will check out how to do it, but now I'm plenty full of work in my startup. Anyway, please, try to be more descriptive next time. I keep you updated ;)

**Comment by ivoriginal** [comment]
keloke?
