### ISSUE TITLE
Gulp replace quotes

### ISSUE THREAD

**Issue by CodingCarlos** [CodingCarlos/inapp-support#5]
Replace all the quotes in templates for the right characters to avoid problems like:
`font-family: 'Roboto'; `
Fix it changing it for:
`font-family:\'Roboto\';`

If not, it became an error like this:

`ias += '<style>    #ias {        font-family: 'Roboto';` 
(in chat.js:103)

**Comment by CodingCarlos** [comment]
I have done some try on a82c997 applying to all templates `.replace(/(\')/gm,"\\'")` but I don't know if this is the best way. What do you think, @UlisesGascon ?

**Comment by UlisesGascon** [comment]
I think... that I know were is the mistake :)

**Comment by UlisesGascon** [comment]
I will add this `.replace(/(\")/gm,'\\\"')` case too
