### ISSUE TITLE
Securization

### ISSUE THREAD

**Issue by CodingCarlos** [CodingCarlos/inapp-support#6]
More than an issue, is a thing to think. How is this going to work? Becouse I don't want to manage any securization in the chat. It shall be part of the app that integrates it. 

But... How shall be the rules to avoid trolling? How shall be the server side to enable firebase authentication in your own server? How that affects to the message structure? How can we make it work with and without authentication?

Maybe a coffe with @UlisesGascon could be a good way to check this out.

**Comment by UlisesGascon** [comment]
What about a coffee at Campus ... 26th? We will need the whiteboard :D

**Comment by CodingCarlos** [comment]
Yap, it sounds good.

**Comment by CodingCarlos** [comment]
When we do some tests, and see the code does not need any change, we'll mark this as done, and will be ready for 0.1 milestone ^^
